# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Técnicas de Gráficos por Computadora
description: > # this means to ignore newlines until "show_excerpts:"
 Página web de Técnicas de Gráficos por Computadora de la UTN FRBA.
author: TGC
email: tgcentregas@gmail.com
theme: just-the-docs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tgcutn.com.ar" # the base hostname & protocol for your site
show_excerpts: false # set to true to show excerpts on the homepage

collections_dir: collections
collections:
  material-tutorials:
    output: true
    permalink: /material/tutorials/:name
  monogame-tutorials:
    output: true
    permalink: /job/tutorials/:name
  units:
    output: true
    permalink: /material/notes/:name

# Just the docs
logo: "/images/logotgc.png"
color_scheme: tgc
# Color scheme supports "light" (default) and "dark"
color_scheme: dark
# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "https://github.com/tgc-utn"
  "Youtube":
    - "https://youtube.com/user/tgcentregas"
  "Google group":
    - "https://groups.google.com/g/TecnicasDeGraficosPorComputadora"
  "Discord":
    - "https://discord.gg/FKZ4k39zAr"

aux_links_new_tab: true

plugins:
 - jekyll-seo-tag
